apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: udsver-client
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: udsver-client
        version: v1
    spec:
      securityContext:
        fsGroup: 0
      containers:
      - name: udsver-client
        image: quay.io/saurabh/udsver:latest
        imagePullPolicy: IfNotPresent
        args: [ "-c" ]
        volumeMounts:
        - mountPath: /tmp/udsver
          name: test-volume
      volumes:
        - name: test-volume
          hostPath:
            # directory location on host
            path: /tmp/udsver
            # this field is optional
            # type: Socket 
